# Generated by Django 3.2.15 on 2022-09-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_event', models.CharField(max_length=300, verbose_name='Название мероприятия')),
                ('date_of_event', models.DateTimeField(verbose_name='Дата мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='JuryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_root', models.BooleanField(auto_created=True, default=False, editable=False, verbose_name='Админ ли?')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('job_title', models.CharField(max_length=300, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото профиля')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=300, verbose_name='Название проекта')),
                ('speaker_name', models.CharField(max_length=150, verbose_name='Имя докладчика')),
                ('grade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.events', verbose_name='Проекты')),
            ],
        ),
    ]
