# Generated by Django 3.2.15 on 2022-09-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_project_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('evaluation_criterion', models.TextField(max_length=300, verbose_name='Критерий оценки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.juryuser', verbose_name='Член жюри')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project', verbose_name='Оценённый проект')),
            ],
        ),
    ]
