# Generated by Django 3.2.15 on 2022-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220914_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.BooleanField(null=True),
        ),
    ]
