# Generated by Django 3.2.15 on 2022-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220914_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_root',
            field=models.BooleanField(auto_created=True, editable=False, verbose_name='Админ ли?'),
        ),
    ]
