# Generated by Django 3.2.15 on 2022-09-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220914_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля'),
        ),
    ]
