# Generated by Django 3.2.15 on 2022-09-16 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation_Criterion_and_Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_criterion', models.TextField(max_length=300, verbose_name='Критерий оценки')),
                ('explanation', models.TextField(verbose_name='Пояснение к критерию')),
                ('grade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Член жюри')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project', verbose_name='Оценённый проект')),
            ],
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
