# Generated by Django 3.2.15 on 2022-09-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220916_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='start_event',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='Начало мероприятия'),
        ),
    ]
