# Generated by Django 3.2.15 on 2022-09-18 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_project_start_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation_criterion_and_grades',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Член жюри'),
        ),
        migrations.AlterField(
            model_name='evaluation_criterion_and_grades',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.project', verbose_name='Оценённый проект'),
        ),
    ]
