# Generated by Django 3.2.15 on 2022-09-18 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220918_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation_criterion_and_grades',
            name='author',
        ),
        migrations.RemoveField(
            model_name='evaluation_criterion_and_grades',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='evaluation_criterion_and_grades',
            name='project',
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Оценивший жюри')),
                ('evaluation_criterion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.evaluation_criterion_and_grades', verbose_name='Критерий оценки')),
            ],
        ),
    ]
