# Generated by Django 3.2.15 on 2022-09-18 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_evaluation_criterion_and_grades_evaluation_criterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.project', verbose_name='Оценённый проект'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Оценивший жюри'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='evaluation_criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.evaluation_criterion', verbose_name='Критерий оценки'),
        ),
    ]
