# Generated by Django 4.1 on 2022-10-05 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_grades_event_alter_grades_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='juries',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Судья'),
            preserve_default=False,
        ),
    ]
